[package]
name = "tictactoe"
version = "0.1.0"
authors = ["Ciaran Woodward <cw15g13@soton.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
